name: flutter_nearby_connections_example
description: Demonstrates how to use the flutter_nearby_connections plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # fluttertoast: ^8.0.1-nullsafety.0

  flutter_nearby_connections:
    path: ../

  cupertino_icons: ^0.1.3
  device_info: ^0.4.0+4
  flutter_udid: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true